name: mlflow-project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - packaging 
  - protobuf
  - pip:
    - mlflow
    - pandas
    - scikit-learn
    - matplotlib      
    - seaborn         
    - imbalanced-learn