name: water-potability-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip=21.2.4
  - pandas=1.4.2
  - scikit-learn=1.1.3
  - imbalanced-learn=0.10.1 
  - pip:
    - mlflow==2.1.1
    - dagshub==0.2.8