name: water-potability-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pandas
  - scikit-learn
  - imbalanced-learn= 
  - pip:
    - mlflow==2.19.0
    - dagshub