name: Automated Model Training and Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAGSHUB_URI: https://dagshub.com/giftbyu/mlops.mlflow
  DOCKER_IMAGE_NAME: septbyu/workflow-ci 
  EXPERIMENT_NAME: "WaterPotability_Tuning_CI"
  CONDA_ENV_NAME: "water-potability-env"
  PROJECT_FOLDER: "MLProject_folder"

jobs:
  train-build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: ${{ env.PROJECT_FOLDER }}/conda.yaml
          auto-update-conda: true
          auto-activate-base: false

      - name: Run MLflow Training
        id: train_step
        env:
          MLFLOW_TRACKING_URI: ${{ env.DAGSHUB_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          cd ${{ env.PROJECT_FOLDER }}
          mlflow run . --experiment-name "$EXPERIMENT_NAME" > mlflow_output.txt
          RUN_ID=$(grep -oP "MLflow Run ID: \K[a-f0-9]{32}" mlflow_output.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          cat mlflow_output.txt

      - name: Verify Run ID
        run: |
          echo "RUN_ID: ${{ env.RUN_ID }}"
          if [[ ! "${{ env.RUN_ID }}" =~ ^[a-f0-9]{32}$ ]]; then
            echo "::error::Invalid RUN_ID format"
            exit 1
          fi

      - name: Delay before download
        run: sleep 30

      - name: Download Model Artifacts
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mkdir -p model
          max_retries=5
          retry_delay=30
          
          for i in $(seq 1 $max_retries); do
            echo "Download attempt $i"
            curl -SsfL -u "$DAGSHUB_USER:$DAGSHUB_TOKEN" \
              "https://dagshub.com/api/v1/repos/giftbyu/mlops.mlflow/artifacts/runs/${{ env.RUN_ID }}/model" \
              -o model/model.tar.gz && break
            echo "Download failed. Retrying in $retry_delay seconds..."
            sleep $retry_delay
          done
          
          tar -xzf model/model.tar.gz -C model
          rm model/model.tar.gz

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          cat <<EOT > Dockerfile
          FROM python:3.12-slim
          RUN pip install mlflow==2.19.0 pandas scikit-learn imbalanced-learn
          COPY model /model
          EXPOSE 5000
          CMD ["mlflow", "models", "serve", "-m", "/model", "-p", "5000"]
          EOT

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .
          docker push ${{ env.DOCKER_IMAGE_NAME }}:latest