name: Automated Model Training and Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DAGSHUB_URI: https://dagshub.com/giftbyu/mlops.mlflow
  DOCKER_IMAGE_NAME: giftbyu/workflow-ci
  
  EXPERIMENT_NAME: "WaterPotability_Tuning_CI"
  CONDA_ENV_NAME: "water-potability-env"
  PROJECT_FOLDER: "MLProject_folder"

jobs:
  train-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Set up Miniconda and Create Training Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ${{ env.CONDA_ENV_NAME }}
          environment-file: ${{ env.PROJECT_FOLDER }}/conda.yaml
          auto-update-conda: true
          auto-activate-base: false
          use-only-tar-bz2: true

      - name: 3. Run MLflow Project to Train Tuned Model
        id: train_step
        env:
          MLFLOW_TRACKING_URI: ${{ env.DAGSHUB_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        shell: bash -l {0}
        run: |
          echo "--- Starting MLflow Run ---"
          
          # PERBAIKAN 1: Mengembalikan pembungkus sh -c "..."
          # Ini untuk memastikan pengalihan output (>) diproses dengan benar oleh shell.
          sh -c "mlflow run ${{ env.PROJECT_FOLDER }} --experiment-name '<span class="math-inline">EXPERIMENT\_NAME' \> mlflow\_output\.txt"
          echo "\-\-\- MLflow Run Output \-\-\-"
          cat mlflow\_output\.txt
          echo "\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-"
          RUN\_ID\=</span>(grep -oP "MLflow Run ID: \K.+" mlflow_output.txt | tr -d '[:space:]')
                    
                  
                    if; then
                      echo "::error::Failed to extract RUN_ID from MLflow output. The 'grep' command likely found no match. Aborting."
                      exit 1
                    fi
                    
                    echo "Successfully extracted RUN_ID: $RUN_ID"
                    echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: 4. Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 5. Build and Push Docker Image with the Newly Trained Model
        run: |
          echo "Building Docker image for RUN_ID: <span class="math-inline">\{\{ env\.RUN\_ID \}\}"
          docker build \\
          \-\-build\-arg RUN\_ID\=</span>{{ env.RUN_ID }} \
                      --build-arg MLFLOW_TRACKING_URI=<span class="math-inline">\{\{ env\.DAGSHUB\_URI \}\} \\
          \-\-build\-arg DAGSHUB\_USERNAME\=</span>{{ secrets.DAGSHUB_USERNAME }} \
                      --build-arg DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} \
                      -t ${{ env.DOCKER_IMAGE_NAME }}:latest \
                      -f Dockerfile.
                    
                    echo "Pushing Docker image to Docker Hub..."
                    docker push ${{ env.DOCKER_IMAGE_NAME }}:latest